stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\train.csv
    deps:
    - .\data\raw\train.csv
    - .\src\data\make_dataset.py
    params:
    - build_features.test_split
    - build_features.seed
    outs:
    - .\data\interim\
  build_features:
    cmd: python .\src\features\build_features.py .\data\interim\processed.csv
    deps:
    - .\data\interim\processed.csv
    - .\src\features\build_features.py
    outs:
    - .\data\processed\

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\
    deps:
    - .\data\processed\
    - .\src\models\train_model.py
    outs:
    - .\models\
  visualize:
    cmd: python .\src\visualization\visualize.py .\models\model.joblib .\data\processed\
    deps:
    - .\data\processed\
    - .\models\model.joblib
    - .\src\visualization\visualize.py
    outs:
    - dvclive




metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
